# Generated by Django 2.1.5 on 2019-04-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190425_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_stopped', models.BooleanField(default=True)),
            ],
        ),
    ]
