# Generated by Django 4.1.2 on 2022-10-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizcontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcontrol',
            name='is_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
